name: tsavaari
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Utility Package
  connectivity_plus: ^6.0.3
  intl: ^0.18.0
  logger: ^2.2.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.0
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  device_preview: ^1.1.0
  flutter_animate: ^4.5.0
  screen_brightness: ^2.0.0+2

  #Qr Code
  qr_flutter: ^4.1.0

  #Card Recharge
  crypto: ^3.0.3

  #Icon Packages
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  #Cash free payment
  flutter_cashfree_pg_sdk: ^2.2.0+38

  #State Management Packages
  get: ^4.6.6
  get_storage: ^2.1.1

  #Dropdown package
  dropdown_search: ^5.0.0

  #Http Package
  http: ^1.2.2
  cached_network_image: ^3.4.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.14.1"

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/common/
    - assets/images/banners/
    - assets/images/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
